#Question 1::

In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


#Question 2::

In [10]:
a=np.array([int(input()) for i in range(5)])
b=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((a,b))))

1
4
3
7
2
6
8
9
11
56
[ 1  2  3  4  6  7  8  9 11 56]


#Question 3:

In [12]:
arr=np.array([4,5,6,7,8,9])
print(arr.ndim)
print(arr.size)

1
6


#Question 4:

In [40]:
arr=np.array([1,2,3,4,5,6])
t=arr
t=t[:, np.newaxis]
print(t)
print(arr)
t=arr
t=np.expand_dims(t,axis=1)
print(t)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


#Question 5:

In [22]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.vstack(a))
print(np.hstack(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


#Question 6:

In [35]:
u=np.array([1,2,3,4,5,6,7,8,4,3,2,2])
print(np.unique(u,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([1, 3, 2, 2, 1, 1, 1, 1], dtype=int64))
